services:
  # Container Aplikasi (Laravel)
  pemweb:
    build:
      context: .
      dockerfile: php/Dockerfile 
    container_name: pemweb_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - agri_network
    depends_on:
      - mariadb

  # Container Database
  mariadb:
    image: mariadb:11.4
    container_name: pemweb_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_agri_service
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user_agri
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - agri_network

  # Container Web Server (Nginx)
  nginx_pemweb:
    image: nginx:stable-alpine
    container_name: pemweb_nginx
    restart: unless-stopped
    ports:
      - "80:80"  # Menggunakan Port 80 agar bisa diakses via http://localhost
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - agri_network
    depends_on:
      - pemweb

networks:
  agri_network:
    driver: bridge